# Generated by Django 5.2.8 on 2025-12-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
