# Generated by Django 5.2.8 on 2025-12-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
